### ISSUE TITLE
deleted_by not set when deleting relationship elements

### ISSUE THREAD

**Issue by bastienu** [WildSideUK/Laravel-Userstamps#27] opened 2019-03-18 10:39 UTC
Hello,

I have just executed this code :
```
$compte->votes()->delete();
$compte->propositions()->delete();
$compte->delete();
```

When I go to my database, my user_id is set in the table `comptes`, in `deleted_by`.
But anything is set in the tables `propositions` and `votes` in the `deleted_by` field, event if – of course – my lines are well deleted...

Is it a normal behavior ?
Did I make something wrong ?

Thanks for your answer !
Bastien

**Comment by mattmcdonald-uk** [comment] 2019-03-19 10:19
There is an issue here - will take a look at resolving it later this week, we should be using `onDelete` in the same manner as the SoftDeletes trait. The `deleting` method doesn't fire when relations are deleted as they happen through `Builder` not `Eloquent`.

As a workaround until this is fixed you could use:
```
$compte->votes->each(function ($item) {
    $item->delete();
});
```

**Comment by jevanswater** [comment] 2019-04-02 15:39
Is this the same issue I'm having? 

`bill::where('fileid', $id)->delete()`

triggers the deleted_at timestamp but not the userstamp but

`$bill = bill::where('fileid', $id)->get();`
`bill::destroy($bill[0]->id);`

triggers both correctly.

**Comment by mattmcdonald-uk** [comment] 2019-09-20 10:53
Sorry for the delay in looking at this issue.

This issue is now documented in the [readme](https://github.com/WildSideUK/Laravel-Userstamps/blob/master/README.md#Limitations).

As a workaround, I've introduced helper methods to allow these bulk updates and deletes which bypass Eloquent events. You can read about how those work in the [updated readme](https://github.com/WildSideUK/Laravel-Userstamps/blob/builder-scopes/README.md#Workarounds).

I want to check these helper methods work as intended, so would be grateful @bastienu @jevanswater if you could test the 1.0.0-rc.0 release I published to see if they allow you to perform these bulk updates with correct values set.

**Closed by mattmcdonald-uk** 2019-09-20 10:53 UTC
Labels: bug
